apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: code-pipeline
  annotations:
    scenarios.ai.sap.com/description: "House price prediction"
    scenarios.ai.sap.com/name: "House Price Prediction"
    executables.ai.sap.com/description: "Runs main.py from public Docker image"
    executables.ai.sap.com/name: "House Price Run"
  labels:
    scenarios.ai.sap.com/id: "house-price"
    ai.sap.com/version: "1.0"
spec:
  entrypoint: mypipeline
  templates:
    - name: mypipeline
      steps:
        - - name: runmodel
            template: mycodeblock1

    - name: mycodeblock1
      container:
        image: docker.io/chetankommula/house-price:03
        command: ["/bin/sh", "-c"]
        args:
          - "python /app/main.py"
