apiVersion: ai.sap.com/v1alpha1
kind: ExecutableTemplate
metadata:
  name: blob-delete-parts
  annotations:
    scenarios.ai.sap.com/name: "Code (Tutorial)"
    scenarios.ai.sap.com/description: "Delete only part-*.csv files (parallel)"
    executables.ai.sap.com/name: "delete-parts"
    executables.ai.sap.com/description: "Delete parts"
  labels:
    ai.sap.com/version: "5.0"
spec:
  inputs:
    parameters:
      - name: prefix
        type: string
      - name: workers
        type: integer
        default: 256
      - name: AZURE_ACCOUNT_URL
        type: string
      - name: AZURE_SAS_TOKEN
        type: string
      - name: AZURE_CONTAINER
        type: string
  template:
    apiVersion: "v1"
    kind: Pod
    metadata:
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      restartPolicy: Never
      imagePullSecrets:
        - name: credstutorialrepo
      containers:
      - name: worker
        image: "docker.io/chetankommula/blob-tools:latest"
        imagePullPolicy: Always
        command: ["python"]
        args:
          - "app.py"
          - "delete-parts"
          - "--prefix"
          - "{{inputs.parameters.prefix}}"
          - "--workers"
          - "{{inputs.parameters.workers}}"
        env:
          - name: AZURE_ACCOUNT_URL
            value: "{{inputs.parameters.AZURE_ACCOUNT_URL}}"
          - name: AZURE_SAS_TOKEN
            value: "{{inputs.parameters.AZURE_SAS_TOKEN}}"
          - name: AZURE_CONTAINER
            value: "{{inputs.parameters.AZURE_CONTAINER}}"
