apiVersion: ai.sap.com/v1alpha1
kind: ExecutableTemplate
metadata:
  name: blob-list
  annotations:
    scenarios.ai.sap.com/name: "Blob Ops"
    scenarios.ai.sap.com/description: "List 'directories' under a prefix in Azure Blob"
    executables.ai.sap.com/name: "list"
    executables.ai.sap.com/description: "List"
  labels:
    ai.sap.com/version: "1.0"
spec:
  inputs:
    parameters:
      - name: prefix
        type: string
      - name: depth
        type: integer
        default: 2
      - name: AZURE_ACCOUNT_URL
        type: string
      - name: AZURE_SAS_TOKEN
        type: string
      - name: AZURE_CONTAINER
        type: string
  template:
    apiVersion: "v1"
    metadata:
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      restartPolicy: Never
      imagePullSecrets:
        - name: credstutorialrepo
      containers:
      - name: worker
        image: "docker.io/chetankommula/blob-tools:latest"
        command: ["python"]
        args:
          - "app.py"
          - "list"
          - "--prefix" ; "{{inputs.parameters.prefix}}"
          - "--depth"  ; "{{inputs.parameters.depth}}"
        env:
          - name: AZURE_ACCOUNT_URL
            value: "{{inputs.parameters.AZURE_ACCOUNT_URL}}"
          - name: AZURE_SAS_TOKEN
            value: "{{inputs.parameters.AZURE_SAS_TOKEN}}"
          - name: AZURE_CONTAINER
            value: "{{inputs.parameters.AZURE_CONTAINER}}"
