apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: house-metrics-train
  annotations:
    scenarios.ai.sap.com/description: "Learning how to ingest data to workflows"
    scenarios.ai.sap.com/name: "House Price (Tutorial)"
    executables.ai.sap.com/description: "Generate metrics"
    executables.ai.sap.com/name: "training-metrics"
    artifacts.ai.sap.com/housedataset.kind: "dataset"
    artifacts.ai.sap.com/housemodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "learning-datalines"
    ai.sap.com/version: "16.0"
spec:
  imagePullSecrets:
    - name: credstutorialrepo
  entrypoint: mypipeline
  arguments:
    parameters:
      - name: DT_MAX_DEPTH
  templates:
    - name: mypipeline
      steps:
        - - name: mypredictor
            template: mycodeblock1
    - name: mycodeblock1
      inputs:
        artifacts:
          - name: housedataset
            path: /argo/inputs/artifacts/housedataset
      outputs:
        artifacts:
          - name: housepricemodel
            globalName: housemodel
            path: /app/model/
            archive:
              none: {}
      container:
        image: docker.io/chetankommula/house-price:metrics
        command: ["/bin/sh", "-c"]
        env:
          - name: DT_MAX_DEPTH
            value: "{{workflow.parameters.DT_MAX_DEPTH}}"
          - name: AICORE_EXECUTION_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['ai.sap.com/execution-id']
        args:
          - "cp /argo/inputs/artifacts/housedataset /app/data/train.csv && python /app/src/main.py"
