apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: data-pipeline
  annotations:
    scenarios.ai.sap.com/description: "Learning how to ingest data to workflows"
    scenarios.ai.sap.com/name: "House Price (Tutorial)"
    executables.ai.sap.com/description: "Train with live data"
    executables.ai.sap.com/name: "training"
    artifacts.ai.sap.com/housedataset.kind: "dataset"
  labels:
    scenarios.ai.sap.com/id: "learning-datalines"
    ai.sap.com/version: "1.0"
spec:
  imagePullSecrets:
    - name: credstutorialrepo
  entrypoint: mypipeline
  templates:
  - name: mypipeline
    steps:
    - - name: mypredictor
        template: mycodeblock1
  - name: mycodeblock1
    inputs:
      artifacts:
        - name: housedataset
          path: /app/data/
    container:
      image: docker.io/chetankommula/house-price:03
      command: ["/bin/sh", "-c"]
      env:
        - name: DT_MAX_DEPTH
          value: "3"
      args:
        - "python /app/src/main.py"
