apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: house-price-server
  annotations:
    scenarios.ai.sap.com/description: "Create online server to make live predictions"
    scenarios.ai.sap.com/name: "House Price (Tutorial)"
    executables.ai.sap.com/description: "Online prediction server"
    executables.ai.sap.com/name: "server"
    artifacts.ai.sap.com/housemodel.kind: "model"  # Match output name from training
  labels:
    scenarios.ai.sap.com/id: "learning-datalines"
    ai.sap.com/version: "2.0"
spec:
  inputs:
    artifacts:
      - name: housemodel  # MUST match training output artifact
    parameters:
      - name: greetmessage
        type: string
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
          - name: credstutorialrepo
        minReplicas: 1
        maxReplicas: 3  # Updated to recommended max
        containers:
          - name: kserve-container
            image: docker.io/chetankommula/house-price:serve
            ports:
              - containerPort: 9001
                protocol: TCP
            command: ["/bin/sh", "-c"]
            args:
              - >
                set -e && echo "Starting" && gunicorn --chdir /app/src main:app -b 0.0.0.0:9001
            env:
              - name: STORAGE_URI
                value: "{{inputs.artifacts.housemodel}}"
              - name: greetingmessage
                value: "{{inputs.parameters.greetmessage}}"
